# modules/pdf_generation.py
# PDF Generation using WeasyPrint for reliable HTML to PDF conversion

import os
import tempfile
from datetime import datetime, timedelta
from flask import render_template_string, current_app
from weasyprint import HTML, CSS
from weasyprint.text.fonts import FontConfiguration
from modules.database import load_conversation_enhanced, get_db_connection
from modules.utils import safe_filename

# PDF Generation Templates
REPORT_TEMPLATE = '''
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
    <style>
        @page {
            size: A4;
            margin: 1in;
            @top-right { content: "Page " counter(page) " of " counter(pages); }
            @top-left { content: "{{ report_type }} - {{ date }}"; }
        }
        
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            line-height: 1.6;
            color: #333;
            margin: 0;
            padding: 0;
        }
        
        .report-header {
            text-align: center;
            margin-bottom: 2rem;
            border-bottom: 2px solid #6366f1;
            padding-bottom: 1rem;
        }
        
        .report-title {
            font-size: 2rem;
            font-weight: 700;
            color: #1f2937;
            margin: 0;
        }
        
        .report-subtitle {
            font-size: 1rem;
            color: #6b7280;
            margin: 0.5rem 0 0 0;
        }
        
        .section {
            margin-bottom: 2rem;
            page-break-inside: avoid;
        }
        
        .section-title {
            font-size: 1.5rem;
            font-weight: 600;
            color: #374151;
            margin-bottom: 1rem;
            border-bottom: 1px solid #e5e7eb;
            padding-bottom: 0.5rem;
        }
        
        .conversation-turn {
            margin-bottom: 1.5rem;
            background: #f9fafb;
            border-radius: 8px;
            padding: 1rem;
        }
        
        .message {
            margin-bottom: 0.75rem;
        }
        
        .message-header {
            font-weight: 600;
            color: #6366f1;
            margin-bottom: 0.25rem;
        }
        
        .message-content {
            color: #374151;
            white-space: pre-wrap;
        }
        
        .stats-grid {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
            gap: 1rem;
            margin: 1rem 0;
        }
        
        .stat-box {
            background: #f3f4f6;
            padding: 1rem;
            border-radius: 6px;
            text-align: center;
        }
        
        .stat-number {
            font-size: 2rem;
            font-weight: 700;
            color: #059669;
        }
        
        .stat-label {
            color: #6b7280;
            font-size: 0.875rem;
        }
        
        .page-break {
            page-break-before: always;
        }
        
        .footer-info {
            margin-top: 2rem;
            padding-top: 1rem;
            border-top: 1px solid #e5e7eb;
            font-size: 0.875rem;
            color: #6b7280;
            text-align: center;
        }
    </style>
</head>
<body>
    <div class="report-header">
        <h1 class="report-title">{{ title }}</h1>
        <p class="report-subtitle">{{ subtitle }}</p>
    </div>
    
    {% if stats %}
    <div class="section">
        <h2 class="section-title">Summary Statistics</h2>
        <div class="stats-grid">
            {% for stat in stats %}
            <div class="stat-box">
                <div class="stat-number">{{ stat.value }}</div>
                <div class="stat-label">{{ stat.label }}</div>
            </div>
            {% endfor %}
        </div>
    </div>
    {% endif %}
    
    {% if conversations %}
    <div class="section">
        <h2 class="section-title">Conversation History</h2>
        {% for turn in conversations %}
        <div class="conversation-turn">
            <div class="message">
                <div class="message-header">You</div>
                <div class="message-content">{{ turn.user }}</div>
            </div>
            {% for voice, reply in turn.responses.items() %}
            <div class="message">
                <div class="message-header">{{ voice }}</div>
                <div class="message-content">{{ reply }}</div>
            </div>
            {% endfor %}
        </div>
        {% endfor %}
    </div>
    {% endif %}
    
    <div class="footer-info">
        Generated by Ghostline Creative Intelligence System<br>
        Report created on {{ generation_date }}
    </div>
</body>
</html>
'''

def generate_pdf_from_html(html_content, output_path=None, options=None):
    """Generate PDF from HTML content using WeasyPrint"""
    default_options = {
        'format': 'A4',
        'margin': '1in',
        'enable_hinting': True
    }
    
    if options:
        default_options.update(options)
    
    try:
        # Create font configuration for better rendering
        font_config = FontConfiguration()
        
        # Create WeasyPrint HTML object
        html_doc = HTML(string=html_content)
        
        # Basic CSS for better PDF formatting
        base_css = CSS(string='''
            @page {
                size: A4;
                margin: 1in;
                @top-right {
                    content: "Page " counter(page) " of " counter(pages);
                    font-size: 10px;
                }
                @top-left {
                    content: "Ghostline Report";
                    font-size: 10px;
                }
            }
            body {
                font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
                font-size: 12px;
                line-height: 1.4;
            }
            .page-break { page-break-before: always; }
        ''')
        
        # Generate PDF
        if output_path:
            html_doc.write_pdf(output_path, stylesheets=[base_css], font_config=font_config)
            with open(output_path, 'rb') as f:
                pdf_bytes = f.read()
        else:
            pdf_bytes = html_doc.write_pdf(stylesheets=[base_css], font_config=font_config)
        
        return pdf_bytes
        
    except Exception as e:
        current_app.logger.error(f"PDF generation failed: {e}")
        raise

def generate_project_report(project_name, date_range_days=30):
    """Generate comprehensive project report"""
    try:
        # Load conversation data
        conversations = load_conversation_enhanced(project_name, limit=100)
        
        # Calculate stats
        total_conversations = len(conversations)
        total_messages = sum(len(turn.get('responses', {})) + 1 for turn in conversations)
        
        # Filter by date range if conversations have timestamps
        cutoff_date = datetime.now() - timedelta(days=date_range_days)
        recent_conversations = conversations  # TODO: Add date filtering when timestamps available
        
        stats = [
            {'value': total_conversations, 'label': 'Total Conversations'},
            {'value': total_messages, 'label': 'Total Messages'},
            {'value': f'{date_range_days} days', 'label': 'Report Period'},
            {'value': len(recent_conversations), 'label': 'Recent Activity'}
        ]
        
        # Render HTML
        html_content = render_template_string(
            REPORT_TEMPLATE,
            title=f"{project_name} Project Report",
            subtitle=f"Intelligence Summary for {date_range_days}-day period",
            report_type="Project Report",
            date=datetime.now().strftime("%Y-%m-%d"),
            conversations=conversations[-20:],  # Last 20 conversations
            stats=stats,
            generation_date=datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        )
        
        return html_content
        
    except Exception as e:
        current_app.logger.error(f"Report generation failed for {project_name}: {e}")
        raise

async def generate_project_pdf(project_name, date_range_days=30, output_path=None):
    """Generate project report as PDF"""
    try:
        html_content = generate_project_report(project_name, date_range_days)
        
        if not output_path:
            safe_name = safe_filename(f"{project_name}_report_{datetime.now().strftime('%Y%m%d')}")
            output_path = f"/tmp/{safe_name}.pdf"
        
        pdf_bytes = await generate_pdf_from_html(html_content, output_path)
        return pdf_bytes, output_path
        
    except Exception as e:
        current_app.logger.error(f"PDF generation failed for {project_name}: {e}")
        raise

def generate_daily_briefing_report(date=None):
    """Generate daily intelligence briefing report"""
    if not date:
        date = datetime.now().date()
    
    try:
        # Get database stats for the day
        stats = []
        
        with get_db_connection() as conn:
            if conn:
                cursor = conn.cursor()
                
                # Count conversations from today
                cursor.execute('''
                    SELECT COUNT(*) FROM chat_threads 
                    WHERE DATE(created_at) = %s
                ''', (date,))
                daily_conversations = cursor.fetchone()[0]
                
                # Count total messages
                cursor.execute('''
                    SELECT COUNT(*) FROM chat_threads
                ''')
                total_conversations = cursor.fetchone()[0]
                
                stats = [
                    {'value': daily_conversations, 'label': 'Today\'s Conversations'},
                    {'value': total_conversations, 'label': 'Total Conversations'},
                    {'value': date.strftime('%A'), 'label': 'Day of Week'}
                ]
        
        # Render HTML
        html_content = render_template_string(
            REPORT_TEMPLATE,
            title="Daily Intelligence Briefing",
            subtitle=f"Activity Summary for {date.strftime('%B %d, %Y')}",
            report_type="Daily Briefing",
            date=date.strftime("%Y-%m-%d"),
            conversations=[],  # Could add recent conversations here
            stats=stats,
            generation_date=datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        )
        
        return html_content
        
    except Exception as e:
        current_app.logger.error(f"Daily briefing generation failed for {date}: {e}")
        raise

async def generate_daily_briefing_pdf(date=None, output_path=None):
    """Generate daily briefing as PDF"""
    if not date:
        date = datetime.now().date()
    
    try:
        html_content = generate_daily_briefing_report(date)
        
        if not output_path:
            safe_name = safe_filename(f"daily_briefing_{date.strftime('%Y%m%d')}")
            output_path = f"/tmp/{safe_name}.pdf"
        
        pdf_bytes = await generate_pdf_from_html(html_content, output_path)
        return pdf_bytes, output_path
        
    except Exception as e:
        current_app.logger.error(f"Daily briefing PDF generation failed for {date}: {e}")
        raise

# Sync wrapper functions for Flask routes
def sync_generate_project_pdf(project_name, date_range_days=30, output_path=None):
    """Synchronous wrapper for project PDF generation"""
    try:
        loop = asyncio.new_event_loop()
        asyncio.set_event_loop(loop)
        return loop.run_until_complete(
            generate_project_pdf(project_name, date_range_days, output_path)
        )
    finally:
        loop.close()

def sync_generate_daily_briefing_pdf(date=None, output_path=None):
    """Synchronous wrapper for daily briefing PDF generation"""
    try:
        loop = asyncio.new_event_loop()
        asyncio.set_event_loop(loop)
        return loop.run_until_complete(
            generate_daily_briefing_pdf(date, output_path)
        )
    finally:
        loop.close()