app = "ghostline-online"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "5000"
  CHAT_MODEL = "openrouter/auto"

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 2
  memory_mb = 8192

[mounts]
  source = "ghostline_data"
  destination = "/app/data"
  initial_size = "1gb"