services:
  - type: web
    name: ghostline
    env: docker
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: FLASK_SECRET_KEY
        sync: false
      - key: GHOSTLINE_PASSWORD
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: CHAT_MODEL
        value: "openrouter/auto"
        sync: false